appcues/wysiwyg

- src/components/EditorWrapper.js
- src/components/Zone.js
- src/editor-actions/Code.js
also remove reduce unnecessary actions
> html-editor: change copy/styling of saved/unsaved text

- src/editor-actions/Code.js
- src/editors/video/VideoEditor.js
- src/editors/video/VideoEditorToolbar.js
and also set a minimum height so we can remove the video editor
> video-editor: don't remove script tags

- src/editor-actions/ImageUpload.js
- src/editor-actions/ImageUploadWithPresets.js
- src/editors/hero/HeroEditor.js
- src/editors/hero/HeroToolbar.js
> hero: add preset options

- src/editor-actions/ImageUploadWithPresets.js
- src/helpers/styles/editor.js
@chelliah I got some comments about the hero selector and emoji selector being too small, what do you think of these increases
> image-presets: increase height

- src/editor-actions/ImageUploadWithPresets.js
Highlighting the box looked weird so I went with a dot
> image-selector: highlight selected item

- src/components/DropDownButton.js
- src/components/DropDownMenu.js
- src/editor-actions/UserProperty.js
- src/helpers/styles/editor.js
- src/icons/DownButton.js
- src/icons/RightButton.js
- added icons to indicate state
- reduced border px to make it look less like a button
> Dropdown Menu: Make it look more like a dropdown

- src/editor-actions/ButtonAction.js
- src/editors/button/ButtonEditor.js
- src/helpers/constants.js
> Buttons: Add new action for Appcues show

- src/components/AddButtonHorizRule.js
- src/components/EditorSelector.js
move to the left side when step is positioned on right side
> Move add component btn

- src/editor-actions/ButtonAction.js
- src/editor-actions/ImageOnClick.js
- src/editors/image/ImageEditor.js
- src/editors/image/ImageToolbar.js
- src/helpers/constants.js
- src/helpers/styles/editor.js
> Image: Add new action to trigger Appcues flow

- src/editor-actions/Code.js
Slideout before:
Slideout after:
Tooltip before (you can scroll to see the rest):
Tooltip after:
> Fix: HTML positioning logic

- src/components/ColorPicker.js
- src/components/Zone.js
- src/editor-actions/BackgroundColor.js
- src/editor-actions/FontColor.js
- src/editors/button/ButtonToolbar.js
- src/editors/richtext/RichTextEditor.js
This pr replaces the existing color picker with a custom one, which now allows for the input of a hex value
> wip: add custom color input

- package.json
remove relative positioning in row containers and canvas
> version: bump to 1.14.0

- src/components/Zone.js
> zone-container: remove relative positioning

- src/components/ColorPicker.js
- src/components/Zone.js
- src/editor-actions/BackgroundColor.js
- src/editor-actions/FontColor.js
- src/editors/button/ButtonToolbar.js
- src/editors/richtext/RichTextEditor.js
- src/helpers/utils.js
I screwed up the commit history, This PR adds a color picker with an input for hex/rgb
values
> Add custom color picker

- src/components/Canvas.js
- src/editors/richtext/RichTextEditor.js
Pairs nicely with appcues/crx-ui#196.
> Fix placeholder position.

- src/components/Toolbar.js
- src/editor-actions/InputFieldOptions.js
- src/editors/form-text/TextInputEditor.js
- src/helpers/constants.js
> Small Text Input: Add types as an option

- src/components/ImageUploader.js
- src/editors/image/ImageEditor.js
Added stripping logic right on the upload response object as well as other edge case
> Img Upload: Make absolutely sure to strip protocol on img upload

- src/helpers/draft/convert.js
> Fix font styling not sticking to correct text

- src/editor-actions/EmojiSelector.js
This PR:
1. Makes the emoji default to 50px
2. Persists a size change to the emoji across emoji changes
> Emoji sizing fix

- src/components/DropDownMenu.js
- src/components/FocusableInput.js
- src/editor-actions/UserProperty.js
- src/editors/richtext/RichTextEditor.js
- src/helpers/styles/editor.js
This removes the auto adding from the previous ui and instead asks a user to insert user properties. It also allows for the adding of custom fallback text for the user.
> Clarified the UI for user property selections

- src/icons/IconButton.js
Fixes https://trello.com/c/GrlPxpn3
> Prevent toolbar items appearing above other elements

- src/components/AddButtonHorizRule.js
- src/editor-actions/ButtonAction.js
- src/icons/AddButton.js
> Add Row Button: Re-center and add animation

- src/components/AddButtonArea.js
- src/components/EditorSelector.js
> Editor popup position fix
